### ISSUE TITLE
No CONTRIBUTING.md

### ISSUE THREAD

**Issue by wilrnh** [vimeo/turnstile-android#21]
#### Issue Summary
Could not find a CONTRIBUTING.md

#### Reproduction Steps
Click on the link to CONTRIBUTING.md in the README.md.

#### Expected Behavior
Finding a CONTRIBUTING.md

#### Actual Behavior
Not finding a CONTRIBUTING.md

**Comment by anthonycr** [comment]
Closing as the link has been fixed
